spring:
   datasource:
      url: jdbc:mysql://localhost/heladeria
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
   jpa:
      open-in-view: false
      show-sql: true
      hibernate:
         ddl-auto: create-drop
      properties:
         hibernate:
            format_sql: true
server:
   servlet.encoding.charset: UTF-8
   servlet.encoding.force: true